### ISSUE TITLE
Server shutdown and reconnect options

### ISSUE THREAD

**Issue by nickiv** [cretz/node-tds#3]
Cretz, your work is really great! Api is awesome and pretty full.

I just found some issues related to network problems and server shutdown.

For instance, if SQL server is stopped between connect and statement.execute, exception is thrown:

/usr/local/lib/node_modules/tds/lib/tds-client.js:104
      throw new Error('Client must be in LOGGED IN state before executing sql'
            ^
Error: Client must be in LOGGED IN state before executing sql
    at TdsClient.sqlBatch (/usr/local/lib/node_modules/tds/lib/tds-client.js:104:13)
    at Statement.<anonymous> (/usr/local/lib/node_modules/tds/lib/tds.js:256:37)
    at Statement.execute (/usr/local/lib/node_modules/tds/lib/tds.js:2:59)
    at Object.doQuery [as _onTimeout](/root/nickiv/node/tds.js:45:7)
    at Timer.ontimeout (timers.js:84:39)

Can you give some advice on how to handle network outage and server restarts with your client?

**Comment by cretz** [comment]
As one of the TODO's at the bottom of the page I listed an "end" event on the connection as a way to determine socket death, but I haven't implemented it even though it is very simple to do. Once I do that, I recommend using that method.

Overall, the client sits in several states. Once the socket connection is terminated, the client rolls back to it's initial state which means you can then connect and login all over again without recreating anything or tearing anything down yet. I just missed the important part: knowing when it's actually dead. I will solve this soon.

**Comment by cretz** [comment]
Reopened pending release so it is clear this has not been published to NPM
